In [1]:
import numpy as np

In [2]:
array_one = np.array([1, 2, 3, 4])
array_one

array([1, 2, 3, 4])

In [3]:
numbers = [9, 8, 7, 6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [4]:
array_of_zeros = np.zeros((3,4))  #creates the array of sets we specify and initilize all the elements to zero
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
array_of_ones = np.ones((3,4))  #creates the array of sets we specify and initilize all the elements to ones
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [7]:
array_empty = np.empty((2,3))
array_empty

array([[2.11034884e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [8]:
array_eye = np.eye(3)  # sets up square matrix with ones along the diagonal and rest with zeros
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
array_of_evens = np.arange(2, 20, 2)  #arange sets up arrays with specific values, takes start value and end value which is exclusive and step function to create an array
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
array_of_floats = np.arange(0, 2, 0.3)  #step size can also be floating points
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
array_2d = np.array([(2,4,6),(3,5,7)])  #creates two dimensional array if list of list is passed
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

### Every NumPy array has shape member variable that determine the dimension of the array

In [12]:
array_2d.shape

(2, 3)

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
array_ones = np.ones_like(array_nd)  #creates array with same dimensions as parameter but with all ones as array elements, it perfills all elements with ones
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])