In [1]:
import numpy as np

In [4]:
a = np.arange(11)**2

In [5]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [7]:
students = np.array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
                    [65, 78, 90, 81],
                    [71, 82, 79, 92]])

In [8]:
for i in students:  #This iterates over elements in first dimension
    print('i = ', i)

i =  ['Alice' 'Beth' 'Cathy' 'Dorothy']
i =  ['65' '78' '90' '81']
i =  ['71' '82' '79' '92']


In [9]:
for element in students.flatten(): #flatten allows us to iterate over every element in array 
                                    #row major flattening - elements in a row appear together
    print(element)

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


In [11]:
for element in students.flatten(order='F'):  #column major flattening - elements in a column appear together 
    print(element)

Alice
65
71
Beth
78
82
Cathy
90
79
Dorothy
81
92


In [12]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
for i in np.nditer(x, order = 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


## flatten vs. nditer

### flatten actually returns a result array, nditer just allows you to iterate over elements

In [17]:
for i in np.nditer(x, order = 'F', flags = ['external_loop']): #iterate column-wise - each column is a 1-D array, iterates only over external looptt
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [18]:
for arr in np.nditer(x):
    arr[...] = arr * arr

ValueError: assignment destination is read-only

In [19]:
for arr in np.nditer(x, op_flags = ['readwrite']):
    arr[...] = arr * arr

In [20]:
x

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])